export const blogConfig = {
    // 头像剪切未圆形
    roundAvatar: true,
    description: "致力于编码实践",
    intro: "/intro.html",
    medias: {
        Baidu: "https://www.bwidu.com",
        BiliBili: "https://bilibili.com",
        // Bitbucket: "https://example.com",
        // Dingding: "https://example.com",
        // Discord: "https://example.com",
        // Dribbble: "https://example.com",
        Email: "mailto:3398775460@qq.com",
        // Evernote: "https://example.com",
        // Facebook: "https://example.com",
        // Flipboard: "https://example.com",
        Gitee: "https://gitee.com/huang-ruifang",
        GitHub: "https://github.com/hrf-666",
        // Gitlab: "https://example.com",
        // Gmail: "mailto:info@example.com",
        // Instagram: "https://example.com",
        // Lark: "https://example.com",
        // Lines: "https://example.com",
        // Linkedin: "https://example.com",
        // Pinterest: "https://example.com",
        // Pocket: "https://example.com",
        // QQ: "https://example.com",
        // Qzone: "https://example.com",
        // Reddit: "https://example.com",
        // Rss: "https://example.com",
        // Steam: "https://example.com",
        // Twitter: "https://example.com",
        Wechat: "https://example.com",
        // Weibo: "https://example.com",
        // Whatsapp: "https://example.com",
        // Youtube: "https://example.com",
        Zhihu: "https://example.com",
        // MrHope: ["https://mister-hope.com", MR_HOPE_AVATAR],
    },
}
